"""
Mitigation helpers.

This file provides a safe, pluggable mitigation interface:
- add_to_blocklist(ip) appends to realtime/blocklist.txt
- apply_block(ip, mode='dry-run') is a NO-OP in dry-run (safe default).
  If mode == 'apply', it returns the system command that SHOULD be run to block the IP
  using iptables/ufw depending on platform. The function intentionally does NOT execute system commands
  by default to avoid accidental modifications to the host firewall.
"""

import os
import platform
from typing import Optional

BLOCKLIST_PATH = os.path.join(os.path.dirname(__file__), "blocklist.txt")


def _ensure_blocklist_exists():
    d = os.path.dirname(BLOCKLIST_PATH)
    if d and not os.path.exists(d):
        os.makedirs(d, exist_ok=True)
    if not os.path.exists(BLOCKLIST_PATH):
        with open(BLOCKLIST_PATH, "w") as fh:
            fh.write("# blocklist generated by CyberSentinel\n")


def add_to_blocklist(ip: str) -> None:
    _ensure_blocklist_exists()
    ip = ip.strip()
    # basic validation
    try:
        import ipaddress

        ipaddress.ip_address(ip)
    except Exception:
        return
    with open(BLOCKLIST_PATH, "r+") as fh:
        lines = [l.strip() for l in fh.readlines()]
        if ip in lines:
            return
        fh.write(ip + "\n")


def apply_block(ip: str, mode: str = "dry-run") -> Optional[str]:
    """
    Returns the command that would be run to block the ip.
    If mode == 'apply', returns the command string (but still does NOT execute it).
    This avoids accidental network changes while allowing operators to inspect the command.
    """
    system = platform.system().lower()
    cmd = None
    if system == "linux":
        cmd = f"sudo iptables -A INPUT -s {ip} -j DROP"
    elif system == "darwin":
        cmd = f"echo 'on macOS use pfctl to block {ip} (manual step)'"
    elif system == "windows":
        cmd = f"netsh advfirewall firewall add rule name=\"Block {ip}\" dir=in action=block remoteip={ip}"
    else:
        cmd = f"# Unknown OS; please block {ip} on your firewall"

    if mode == "apply":
        # Intentionally do not run the command here. Operator must run manually or call from secure operator tool.
        return cmd
    return cmd
